---
language: java
sudo: true
jdk: oraclejdk8
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
before_install:
  - sudo apt-get -qq update
  - git clone https://github.com/open-source-parsers/jsoncpp.git
  - cd jsoncpp
  - python amalgamate.py
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cp src/lib_json/libjsoncpp.a /usr/local/lib/
script: echo 'hella' #mvn install -Dlog4j.configurationFile="src/test/resources/log4j.xml" -DskipTests -B