---
language: java
sudo: false
jdk: oraclejdk8
before_install:
 - git clone https://github.com/open-source-parsers/jsoncpp.git
 - python jsoncpp/amalgamate.py
script: mvn install -Dlog4j.configurationFile="src/test/resources/log4j.xml" -DskipTests -B